###############################################################################
# Makefile (and Makefile.def) -- Makefile for the LC-3 tools
#
#  "Copyright (c) 2003 by Steven S. Lumetta."
# 
#  Permission to use, copy, modify, and distribute this software and its
#  documentation for any purpose, without fee, and without written 
#  agreement is hereby granted, provided that the above copyright notice
#  and the following two paragraphs appear in all copies of this software,
#  that the files COPYING and NO_WARRANTY are included verbatim with
#  any distribution, and that the contents of the file README are included
#  verbatim as part of a file named README with any distribution.
#  
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE TO ANY PARTY FOR DIRECT, 
#  INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT 
#  OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE AUTHOR 
#  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  
#  THE AUTHOR SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT 
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
#  A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" 
#  BASIS, AND THE AUTHOR NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, 
#  UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
#
#  Author:		Steve Lumetta
#  Version:		1
#  Creation Date:	18 October 2003
#  Filename:		Makefile[.def]
#  History:		
# 	SSL	2	31 October 2003
# 		Added lc3convert tool into distribution.
# 	SSL	1	18 October 2003
# 		Copyright notices and Gnu Public License marker added.
#
###############################################################################

# These path names are automatically set by configure.
GCC  = __GCC__
FLEX = __FLEX__
EXE  = __EXE__
RM   = __RM__
CP   = __CP__
MKDIR = __MKDIR__
CHMOD = __CHMOD__
SED = __SED__
MAKE = __MAKE__
AR = __AR__
RANLIB = __RANLIB__
INSTALL_DIR = __INSTALL_DIR__
TOP_DIR = __TOP_DIR__
# End of configuration block.

CFLAGS  = -g -m32 -mno-sse
LDFLAGS = -g -m32 -mno-sse
LC3AS   = ./lc3as

librcc_OBJECTS = alloc.o bind.o dag.o dagcheck.o decl.o \
	enode.o error.o expr.o event.o \
	init.o inits.o input.o lex.o list.o \
	main.o output.o prof.o profio.o simp.o stmt.o \
	string.o sym.o \
	trace.o tree.o types.o null.o symbolic.o gen.o \
	bytecode.o alpha.o mips.o lc3.o sparc.o stab.o \
	x86.o x86linux.o

%.o: %.c
	${GCC} -c ${CFLAGS} -o $@ $<

dist: lburg rcc

distclean::
	${RM} -f *.o *~ 
	cd ${TOP_DIR}/lburg && ${MAKE} distclear

distclear: distclean
	${RM} -f rcc${EXE} librcc.a
	cd ${TOP_DIR}/lburg && ${MAKE} distclean

lburg:
	cd ${TOP_DIR}/lburg && ${MAKE} dist

rcc: main.o librcc.a
	${GCC} ${CFLAGS} -o $@ $^

librcc.a: ${librcc_OBJECTS}
	-rm -f librcc.a
	${AR} cru librcc.a ${librcc_OBJECTS}
	${RANLIB} librcc.a

dagcheck.c: dagcheck.md
	${TOP_DIR}/lburg/lburg dagcheck.md dagcheck.c

alpha.c: alpha.md
	${TOP_DIR}/lburg/lburg alpha.md alpha.c

sparc.c: sparc.md
	${TOP_DIR}/lburg/lburg sparc.md sparc.c

mips.c: mips.md
	${TOP_DIR}/lburg/lburg mips.md mips.c

x86.c: x86.md
	${TOP_DIR}/lburg/lburg x86.md x86.c

x86linux.c: x86linux.md
	${TOP_DIR}/lburg/lburg x86linux.md x86linux.c

lc3.c: lc3.md
	${TOP_DIR}/lburg/lburg lc3.md lc3.c
